%% adjust paths to libs and includes if necessary

mex opengv.cpp -IF:/Libraries/OpenGV_Pull/opengv/third_party/ ...
    -IF:/Libraries/OpenGV_Pull/opengv/include/ -LF:/Libraries/OpenGV_Pull/build/lib/Release/ ...
    -lopengv -lrandom_generators
